version: '3.1'

networks:
  proxynet:
    external: true


services:
 
 beaconcli:
    build:
      context: .
      ssh:
        - default
    container_name: beaconcli
    ports:
      - "5060:5050"
    entrypoint: ["sh", "-c", "service ssh restart && tail -f /dev/null"]
    networks:
      - proxynet
